language: 
    python

sudo:
    - "true"

python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - git clone https://github.com/DMTF/Redfish-Mockup-Server.git
    - git clone https://github.com/DMTF/Redfish-Service-Validator.git

branches:
    only:
    - master

script:
    - python3 test_exit.py
    - ls
