language: 
    python

sudo:
    - "true"

python:
    - "2.7"

install:
    - ls
    - pip install -r requirements.txt
    - git clone https://github.com/DMTF/Redfish-Mockup-Server.git
    - git clone https://github.com/DMTF/Redfish-Service-Validator.git
    - mkdir logs
    - wget http://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2016.3.zip
    - unzip -j "DSP8010_2016.3.zip" "DSP8010_2016.3/metadata/*" -d "./metadata"

branches:
    only:
    - master

script:
    - python3 Redfish-Mockup-Server/redfishMockupServer.py & sleep 10
    - python Redfish-Service-Validator/RedfishServiceValidator.py
    - python3 test_exit.py
    - ls
