language: 
    python

sudo:
    - "true"

python:
    - "2.7"

before_install:
    - pip install -r requirements.txt
    - sudo apt-get update
    - sudo apt-get install python3

branches:
    only:
    - master

script:
    - python3 test_exit.py
     
